export const bookingsData = [
  {
    booking_id: "B001",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "John Doe",
    count: 3,
    datesTimes: [{ date: "2023-07-17", start: "09:00 AM", end: "11:00 AM" }],
    reason:
      "Team brainstorming session to discuss new project ideas and strategies.",
  },
  {
    booking_id: "B002",
    booked_resource_id: "R002",
    resource_name: "Studio D",
    username: "Jane Smith",
    count: 5,
    datesTimes: [{ date: "2023-07-18", start: "02:00 PM", end: "04:00 PM" }],
    reason:
      "Photography workshop for beginners to learn essential techniques and improve their skills.",
  },
  {
    booking_id: "B003",
    booked_resource_id: "R003",
    resource_name: "Lab E",
    username: "Michael Brown",
    count: 2,
    datesTimes: [
      { date: "2023-07-19", start: "10:00 AM", end: "01:00 PM" },
      { date: "2023-07-20", start: "02:00 PM", end: "05:00 PM" },
    ],
    reason:
      "Science fair project experimentation to analyze the effects of different environmental factors on plant growth and development.",
  },
  {
    booking_id: "B004",
    booked_resource_id: "R004",
    resource_name: "Auditorium A",
    username: "Emily Wilson",
    count: 10,
    datesTimes: [{ date: "2023-07-21", start: "09:00 AM", end: "12:00 PM" }],
    reason:
      "School assembly to celebrate achievements and recognize outstanding students.",
  },
  {
    booking_id: "B005",
    booked_resource_id: "R005",
    resource_name: "Gymnasium",
    username: "David Johnson",
    count: 20,
    datesTimes: [
      { date: "2023-07-22", start: "01:00 PM", end: "04:00 PM" },
      { date: "2023-07-23", start: "09:00 AM", end: "12:00 PM" },
    ],
    reason: "Fitness workshop for employees to promote health and well-being.",
  },
  {
    booking_id: "B006",
    booked_resource_id: "R006",
    resource_name: "Library",
    username: "Sophia Miller",
    count: 1,
    datesTimes: [
      { date: "2023-07-24", start: "10:00 AM", end: "12:00 PM" },
      { date: "2023-07-25", start: "02:00 PM", end: "04:00 PM" },
      { date: "2023-07-26", start: "10:00 AM", end: "12:00 PM" },
    ],
    reason: "Book club meeting to discuss the latest bestseller.",
  },
  {
    booking_id: "B007",
    booked_resource_id: "R007",
    resource_name: "Computer Lab",
    username: "Oliver Wilson",
    count: 6,
    datesTimes: [
      { date: "2023-07-27", start: "09:00 AM", end: "12:00 PM" },
      { date: "2023-07-28", start: "01:00 PM", end: "04:00 PM" },
    ],
    reason:
      "Training session on software development for beginners to learn coding fundamentals.",
  },
  {
    booking_id: "B008",
    booked_resource_id: "R008",
    resource_name: "Art Studio",
    username: "Ava Davis",
    count: 4,
    datesTimes: [
      { date: "2023-07-29", start: "10:00 AM", end: "12:00 PM" },
      { date: "2023-07-30", start: "02:00 PM", end: "05:00 PM" },
      { date: "2023-07-31", start: "10:00 AM", end: "12:00 PM" },
      { date: "2023-08-01", start: "02:00 PM", end: "05:00 PM" },
    ],
    reason: "Art workshop for intermediate-level painters.",
  },
  {
    booking_id: "B009",
    booked_resource_id: "R009",
    resource_name: "Music Room",
    username: "James Thompson",
    count: 2,
    datesTimes: [
      { date: "2023-08-02", start: "01:00 PM", end: "04:00 PM" },
      { date: "2023-08-03", start: "09:00 AM", end: "12:00 PM" },
      { date: "2023-08-04", start: "01:00 PM", end: "04:00 PM" },
    ],
    reason: "Band rehearsal for the upcoming school concert.",
  },
  {
    booking_id: "B010",
    booked_resource_id: "R008",
    resource_name: "Art Studio",
    username: "Ryan Anderson",
    count: 3,
    datesTimes: [{ date: "2023-08-05", start: "09:00 AM", end: "11:00 AM" }],
    reason: "Project meeting to discuss progress and plan future tasks.",
  },
  {
    booking_id: "B011",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "Robert Davis",
    count: 5,
    datesTimes: [{ date: "2023-08-06", start: "02:00 PM", end: "04:00 PM" }],
    reason: "Client presentation to showcase new product features.",
  },
  {
    booking_id: "B012",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "Ryan Anderson",
    count: 2,
    datesTimes: [
      { date: "2023-08-07", start: "10:00 AM", end: "01:00 PM" },
      { date: "2023-08-08", start: "02:00 PM", end: "05:00 PM" },
    ],
    reason: "Training session on effective communication skills.",
  },
  {
    booking_id: "B013",
    booked_resource_id: "R003",
    resource_name: "Lab E",
    username: "Michael Brown",
    count: 8,
    datesTimes: [{ date: "2023-08-09", start: "09:00 AM", end: "12:00 PM" }],
    reason: "Departmental meeting to review quarterly performance.",
  },
  {
    booking_id: "B014",
    booked_resource_id: "R002",
    resource_name: "Studio D",
    username: "Ryan Anderson",
    count: 4,
    datesTimes: [
      { date: "2023-08-10", start: "10:00 AM", end: "12:00 PM" },
      { date: "2023-08-11", start: "02:00 PM", end: "04:00 PM" },
    ],
    reason: "Workshop on time management and productivity enhancement.",
  },
  {
    booking_id: "B015",
    booked_resource_id: "R007",
    resource_name: "Computer Lab",
    username: "Michael Brown",
    count: 6,
    datesTimes: [
      { date: "2023-08-12", start: "09:00 AM", end: "12:00 PM" },
      { date: "2023-08-13", start: "01:00 PM", end: "04:00 PM" },
    ],
    reason: "Training session on conflict resolution and teamwork.",
  },
  {
    booking_id: "B016",
    booked_resource_id: "R002",
    resource_name: "Studio D",
    username: "Michael Brown",
    count: 3,
    datesTimes: [{ date: "2023-08-14", start: "09:00 AM", end: "11:00 AM" }],
    reason: "Marketing team meeting to discuss upcoming campaigns.",
  },
  {
    booking_id: "B017",
    booked_resource_id: "R003",
    resource_name: "Lab E",
    username: "Ryan Anderson",
    count: 5,
    datesTimes: [{ date: "2023-08-15", start: "02:00 PM", end: "04:00 PM" }],
    reason: "Product development brainstorming session.",
  },
  {
    booking_id: "B018",
    booked_resource_id: "R004",
    resource_name: "Auditorium A",
    username: "Sophia Miller",
    count: 2,
    datesTimes: [
      { date: "2023-08-16", start: "10:00 AM", end: "01:00 PM" },
      { date: "2023-08-17", start: "02:00 PM", end: "05:00 PM" },
    ],
    reason: "Sales training on effective negotiation techniques.",
  },
  {
    booking_id: "B019",
    booked_resource_id: "R002",
    resource_name: "Studio D",
    username: "Ryan Anderson",
    count: 8,
    datesTimes: [{ date: "2023-08-18", start: "09:00 AM", end: "12:00 PM" }],
    reason: "Client meeting to discuss project requirements.",
  },
  {
    booking_id: "B020",
    booked_resource_id: "R007",
    resource_name: "Computer Lab",
    username: "Michael Brown",
    count: 4,
    datesTimes: [
      { date: "2023-08-19", start: "10:00 AM", end: "12:00 PM" },
      { date: "2023-08-20", start: "02:00 PM", end: "04:00 PM" },
    ],
    reason: "Training session on effective presentation skills.",
  },
  {
    booking_id: "B021",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "Sophia Miller",
    count: 6,
    datesTimes: [
      { date: "2023-08-21", start: "09:00 AM", end: "12:00 PM" },
      { date: "2023-08-22", start: "01:00 PM", end: "04:00 PM" },
    ],
    reason: "Team building activity to foster collaboration.",
  },
  {
    booking_id: "B022",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "Chloe Perez",
    count: 3,
    datesTimes: [{ date: "2023-08-23", start: "09:00 AM", end: "11:00 AM" }],
    reason: "Project kick-off meeting for the new marketing campaign.",
  },
  {
    booking_id: "B023",
    booked_resource_id: "R004",
    resource_name: "Auditorium A",
    username: "Daniel Johnson",
    count: 5,
    datesTimes: [{ date: "2023-08-24", start: "02:00 PM", end: "04:00 PM" }],
    reason: "Training session on customer service excellence.",
  },
  {
    booking_id: "B024",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "Harper Lee",
    count: 2,
    datesTimes: [
      { date: "2023-08-25", start: "10:00 AM", end: "01:00 PM" },
      { date: "2023-08-26", start: "02:00 PM", end: "05:00 PM" },
    ],
    reason: "Departmental meeting to align on quarterly goals.",
  },
  {
    booking_id: "B025",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "Sebastian Clark",
    count: 8,
    datesTimes: [{ date: "2023-08-27", start: "09:00 AM", end: "12:00 PM" }],
    reason: "Training session on leadership development.",
  },
  {
    booking_id: "B026",
    booked_resource_id: "R004",
    resource_name: "Auditorium A",
    username: "Ryan Anderson",
    count: 4,
    datesTimes: [
      { date: "2023-08-28", start: "10:00 AM", end: "12:00 PM" },
      { date: "2023-08-29", start: "02:00 PM", end: "04:00 PM" },
    ],
    reason: "Workshop on effective team communication.",
  },
  {
    booking_id: "B027",
    booked_resource_id: "R002",
    resource_name: "Conference Room C",
    username: "Andrew Adams",
    count: 6,
    datesTimes: [
      { date: "2023-08-30", start: "09:00 AM", end: "12:00 PM" },
      { date: "2023-08-31", start: "01:00 PM", end: "04:00 PM" },
    ],
    reason: "Training session on problem-solving techniques.",
  },
  {
    booking_id: "B028",
    booked_resource_id: "R002",
    resource_name: "Studio D",
    username: "Grace Thompson",
    count: 3,
    datesTimes: [{ date: "2023-09-01", start: "09:00 AM", end: "11:00 AM" }],
    reason: "Product demonstration for potential clients.",
  },
  {
    booking_id: "B029",
    booked_resource_id: "R001",
    resource_name: "Conference Room C",
    username: "Ryan Anderson",
    count: 5,
    datesTimes: [{ date: "2023-09-02", start: "02:00 PM", end: "04:00 PM" }],
    reason: "Training session on new software implementation.",
  },
  {
    booking_id: "B030",
    booked_resource_id: "R003",
    resource_name: "Lab E",
    username: "Lily Adams",
    count: 2,
    datesTimes: [
      { date: "2023-09-03", start: "10:00 AM", end: "01:00 PM" },
      { date: "2023-09-04", start: "02:00 PM", end: "05:00 PM" },
    ],
    reason: "Departmental meeting to discuss budget allocation.",
  },
];
